Try to unpair from cloud.
Signed-off-by: Jon Seymour <jon@ninjablocks.com>

diff --git a/bin/sphere-reset b/bin/sphere-reset
--- a/bin/sphere-reset
+++ b/bin/sphere-reset
@@ -33,7 +33,19 @@ clear-cloud() {
 
 reset-credentials() {
 	echo "reset credentials..." 1>&2
-	! test -f /data/etc/opt/ninja/credentials.json || rm /data/etc/opt/ninja/credentials.json
+	if test -f /data/etc/opt/ninja/credentials.json; then
+		set -- $(cat /data/etc/opt/ninja/credentials.json | jq '.|.nodeId+" "+.token' | tr -d \")
+		NODE=$1
+		TOKEN=$2
+		if test -n "$NODE" && test -n "$TOKEN"; then
+			echo "deleting $NODE from cloud..." 1>&2
+			url="https://api.sphere.ninja/rest/v1/node/${NODE}?access_token=${TOKEN}"
+			curl -X DELETE -s "$url"
+		else
+			echo "unable to parse node and token from credentials.json. ignoring unpair."
+		fi
+		rm /data/etc/opt/ninja/credentials.json
+	fi
 	! test -f /data/etc/opt/ninja/mesh.json || rm /data/etc/opt/ninja/mesh.json
 	sync
 }
